insert into Professor values (1,'Jhon Smart')
insert into Professor values (2,'Peter Stiller')
insert into Professor values (3,'Roy Tate')
insert into Professor values (4,'Alfred Smith')

insert into Course values (1,true,25,'Basic','Java Basic',2)
insert into Course values (2,true,12,'Advanced','IT Requirements Management',3)
insert into Course values (3,true,40,'Intermediate','Time Management and personal efficiency',3)
insert into Course values (4,true,16,'Basic','Object Oriented Programming',2)
insert into Course values (5,true,25,'Advanced','Patterns',3)
insert into Course values (6,true,50,'Intermediate','Introduction to JSF',1)
insert into Course values (7,true,100,'Basic','Unit web tests with JWebUnit',3)
insert into Course values (8,true,150,'Intermediate','Spring framework',3)
insert into Course values (9,true,30,'Advanced','Hibernate',2)
insert into Course values (10,true,35,'Basic','JBoss Application Server',3)
insert into Course values (11,true,55,'Intermediate','JBoss Seam',1)
insert into Course values (12,true,30,'Advanced','EJB 3.0',3)
insert into Course values (13,true,12,'Basic','Maven + Struts + Spring + Hibernate',3)
insert into Course values (14,true,10,'Intermediate','Java Security',2)
insert into Course values (15,true,3,'Advanced','Java Intranet Applications',3)
insert into Course values (16,true,16,'Basic','Java and Design Patterns',1)
insert into Course values (17,true,24,'Intermediate','Object Oriented Analisys and Design with UML',3)
insert into Course values (18,true,54,'Advanced','Introduction to new technologies',3)
insert into Course values (19,true,84,'Basic','Web Development with Java',2)
insert into Course values (20,true,22,'Intermediate','Introduction to Liferay',3)